from __future__ import annotations

import sys
import types
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ui.mechanics_reference import SECTION_PAIRS, render_structured_list


class _FakeContext:
    def __init__(self, fake: "_FakeStreamlit") -> None:
        self.fake = fake

    def __enter__(self) -> "_FakeContext":
        self.fake.context_depth += 1
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        self.fake.context_depth -= 1


class _FakeStreamlit(types.SimpleNamespace):
    def __init__(self) -> None:
        super().__init__()
        self.calls: list[tuple[str, Any]] = []
        self.context_depth = 0

    def _record(self, name: str, value: Any = None) -> None:
        self.calls.append((name, value))

    def subheader(self, value: str) -> None:
        self._record("subheader", value)

    def caption(self, value: str) -> None:
        self._record("caption", value)

    def markdown(self, value: str) -> None:
        self._record("markdown", value)

    def dataframe(self, *args: Any, **kwargs: Any) -> None:
        self._record("dataframe", {"args": args, "kwargs": kwargs})

    def table(self, value: Any) -> None:
        self._record("table", value)

    def json(self, value: Any) -> None:
        self._record("json", value)

    def expander(self, label: str, expanded: bool = False) -> _FakeContext:
        self._record("expander", {"label": label, "expanded": expanded})
        return _FakeContext(self)


def main() -> None:
    title_by_key = {key: title for title, key in SECTION_PAIRS}
    expected_titles = {
        "qte_intro_outro": "QTE / Intro / Outro",
        "echo_sets": "Echo Set Effects",
        "weapons": "Weapon Effects",
        "tune_break": "Tune Break System",
        "off_tune": "Off-Tune Level",
        "response_damage": "Tune Response Damage",
        "known_runtime_modes": "Known Runtime Modes",
        "legacy_modes": "Legacy Modes",
        "known_limitations": "Known Limitations",
        "simplified_assumptions": "Simplified Assumptions",
    }
    for key, expected_title in expected_titles.items():
        assert title_by_key.get(key) == expected_title, f"{key} should render as {expected_title!r}"

    ugly_generated_keys = {
        "qte_intro_outro",
        "echo_sets",
        "weapons",
        "tune_break",
        "off_tune",
        "response_damage",
    }
    for key in ugly_generated_keys:
        assert title_by_key[key] != key.replace("_", " ").title(), f"{key} should not use ugly autogenerated title"

    fake = _FakeStreamlit()
    sys.modules["streamlit"] = fake
    render_structured_list(
        "Weapon Effects",
        [
            {
                "name": "Readable Weapon",
                "runtime_effects": [
                    {
                        "name": "Nested Effect",
                        "trigger": "team_heal",
                        "values": {"r1": "+20%"},
                    }
                ],
                "exclusions": ["not reapplied at runtime"],
            }
        ],
    )
    call_names = [name for name, _value in fake.calls]
    assert "expander" in call_names, "list[dict] sections should use cards/expanders"
    assert "markdown" in call_names, "structured content should render as readable markdown"
    assert "dataframe" not in call_names, "Character Mechanics should not default list[dict] to dataframe"
    assert "json" in call_names, "raw JSON should be available only in debug expander"

    print("Mechanics reference readability smoke test passed.")


if __name__ == "__main__":
    main()
